### ISSUE TITLE
Default logic of implementation wrong.

### ISSUE THREAD

**Issue by wontheone1** [unicredit/sbt-swagger-codegen-examples#2]
1. POST(create a resource) creates all resources with a same id(0) only.
2. DELETE(remove a resource) deletes nothing. And I found the reason in the implementation,
   def deletePetImpl(id: Long) = Future {
   
     val found = pets.find(_.id == id).get
     pets = pets.filter(_.id == id) // this should be 'pets = pets.filter(_.id != id)' in my opinion
                                                 // but if we don't fix POST to generate incrementing or different ids, 
                                                 // this line will simply delete all the resources,
                                                 // so it should be fixed with POST 
     found // and also if we change the above line to what I suggested, this 'found' will return 'None.get'
               // so I changed the response to NoContent response as shown below
   }

def deletePet(id: Long) = {
    Action.async(request => {
      deletePetImpl(id).map(answer => NoContent) // this line is changed
    }.recoverWith({
      case (err: Throwable) => {
        onError("deletePet", err).map(errAnswer => BadRequest(errAnswer))
      }
    }))
  }

**Comment by andreaTP** [comment]
Ok we should have a look, please do not care too much on the implementation since is just a reference.

**Comment by andreaTP** [comment]
fixed thanks

**Comment by wontheone1** [comment]
thanks :)
