### ISSUE TITLE
generated client code cannot resolve 'ws'

### ISSUE THREAD

**Issue by wontheone1** [unicredit/sbt-swagger-codegen-examples#3]
I uncommented 'in build.sbt the dependency from play-ws'.
But in the PetStoreClient.scala 
import play.api.libs.ws._ cannot be resolved('ws' part)

p.s. Also how do I use or test client code? I don't know what I can do with client codes I am just using postman.

**Comment by andreaTP** [comment]
To test client code you need to have at least two projects available.
In one you generate the server and run it.
In the other you do not generate the server and just write some code that make use of the client.

did you reload sbt after build.sbt modification?

**Comment by fralken** [comment]
Please check the new client/server example based on sbt-swagger-codegen 0.0.6-SNAPSHOT

**Comment by wontheone1** [comment]
@fralken Hello fralken thanks but I can't build the new example, I think there is a problem. Please check new issue I created.

**Comment by wontheone1** [comment]
@andreaTP Thanks for explanation, I didn't know how to use them, I will try it when I can build with new version.

**Comment by wontheone1** [comment]
Now it I can resolve the ws, the reason could have been I ran generate command for both server and client in the same project it seems. Thank you for the help.
Just one question how do I use this client code ?
under 'sbt-swagger-codegen-examples/client/src/main/scala/swagger/codegen', there are 'client, json' folder and 'Model.scala'. do I need to move them to a Play! application and make some frontend HTML/CSS page and map UI to PetStoreClient functions?
What is the workflow, process to use and test this kind of client codes in general?

**Comment by andreaTP** [comment]
I've updated the example with some code that make use of the client code.
Into the Readme.MD you find instructions on how to run it.

Please note that during this I found an issue on query params that will be fixed shortly. 
( https://github.com/unicredit/sbt-swagger-codegen/issues/18 )

**Comment by wontheone1** [comment]
Thanks !!
