### ISSUE TITLE
Unresolved dependency error in the new version when run  sbt for the first time.

### ISSUE THREAD

**Issue by wontheone1** [unicredit/sbt-swagger-codegen-examples#4]
I clone the project and run sbt in the project base directory and I get the following error,

[info] Loading project definition from /Users/**_/codegen/sbt-swagger-codegen-examples/project
[info] Updating {file:/Users/**_/codegen/sbt-swagger-codegen-examples/project/}myExtensionPlugin...
[info] Resolving eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT ...
[warn]  module not found: eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/eu.unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/eu.unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/wseobseo/.ivy2/local/eu.unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/eu/unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/sbt-swagger-codegen-lib_2.10-0.0.6-SNAPSHOT.pom
[warn] ==== activator-local: tried
[warn]   /Users/wseobseo/activator/repository/eu.unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /Users/wseobseo/.activator/repository/eu.unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/eu/unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/sbt-swagger-codegen-lib_2.10-0.0.6-SNAPSHOT.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/eu.unicredit/sbt-swagger-codegen-lib_2.10/0.0.6-SNAPSHOT/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...

> [warn]    ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]    ::          UNRESOLVED DEPENDENCIES         ::
> [warn]    ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]    :: eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT: not found
> [warn]    ::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn]    Note: Unresolved dependencies path:
> [warn]        eu.unicredit:sbt-swagger-codegen-lib_2.10:0.0.6-SNAPSHOT (/Users/wseobseo/zalando/codegen/sbt-swagger-codegen-examples/project/plugins.sbt#L12)
> [warn]          +- my-extension-plugin:my-extension-plugin:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
> sbt.ResolveException: unresolved dependency: eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT: not found
>   at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
>   at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
>   at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
>   at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
>   at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
>   at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
>   at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
>   at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
>   at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
>   at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
>   at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
>   at xsbt.boot.Using$.withResource(Using.scala:10)
>   at xsbt.boot.Using$.apply(Using.scala:9)
>   at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
>   at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
>   at xsbt.boot.Locks$.apply0(Locks.scala:31)
>   at xsbt.boot.Locks$.apply(Locks.scala:28)
>   at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
>   at sbt.IvySbt.withIvy(Ivy.scala:128)
>   at sbt.IvySbt.withIvy(Ivy.scala:125)
>   at sbt.IvySbt$Module.withModule(Ivy.scala:156)
>   at sbt.IvyActions$.updateEither(IvyActions.scala:168)
>   at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
>   at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
>   at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
>   at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
>   at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
>   at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
>   at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
>   at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
>   at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
>   at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
>   at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
>   at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>   at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>   at sbt.std.Transform$$anon$4.work(System.scala:63)
>   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>   at sbt.Execute.work(Execute.scala:237)
>   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> [error](myExtensionPlugin/*:update) sbt.ResolveException: unresolved dependency: eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT: not found
> Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by andreaTP** [comment]
it looks like sbt do not try to resolve the dependency from Sonatype snapshots repo ....
My output correctly shows:

```
[warn] Choosing sonatype-snapshots for eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT
```

could you double check your connectivity status (proxy etc etc..)?

**Comment by mfirry** [comment]
You may need to try and add `Resolver.sonatypeRepo("snapshots")`.

**Comment by andreaTP** [comment]
> You may need to try and add Resolver.sonatypeRepo("snapshots").

already present
https://github.com/unicredit/sbt-swagger-codegen-examples/blob/master/project/plugins.sbt#L1
should work...

**Comment by wontheone1** [comment]
@andreaTP I checked with https://whatismyipaddress.com/ and firefox setting that we are not connected throw any proxy server. I'd appreciate any advice

**Comment by andreaTP** [comment]
can you retry everything from scratch and post commands and output then?
Cannot understand how to reproduce this sorry :-(

**Comment by andreaTP** [comment]
the library is properly published and available:
https://oss.sonatype.org/content/repositories/snapshots/eu/unicredit/sbt-swagger-codegen-lib_2.10/

**Comment by fralken** [comment]
I added a resolver to sonatype's snapshots in my-estension-plugin. Can you git pull and try again?

**Comment by wontheone1** [comment]
@andreaTP I tried everything from scratch but... , as @fralken suggested, I ran 'git pull' and it builds now thank you very much everyone !!

**Comment by andreaTP** [comment]
Probably we must remove my-extension-plugin entierly since it is for customizations and not direct usage

**Comment by fralken** [comment]
But it shows how to extend the code generator! Instead of removing it, it would be interesting to show how to use the custom generators in practice.

**Comment by andreaTP** [comment]
ok, we can add the related code commented into the build, WDYT?

**Comment by wontheone1** [comment]
Hello, sorry but this way sbt builds something but it didn't generate the src folder when I check in the file system. Also after 'sbt' command, I run 'swaggerCodeGen' as it is the next step, it give me an exception because the source dir doesn't exist. Below I paste my full terminal output. (Also tested with the new project from scratch, the same problem)

> **-08957:sbt-swagger-codegen-examples wseobseo$ sbt
> [info] Loading project definition from /Users/**/**/codegen/sbt-swagger-codegen-examples/project
> [info] Updating {file:/Users/wseobseo/**/**/sbt-swagger-codegen-examples/project/}myExtensionPlugin...
> [info] Resolving eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT ...
> [warn] Unable to reparse eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT from sonatype-snapshots, using Mon Jul 04 17:22:22 EEST 2016
> [warn] Choosing sonatype-snapshots for eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT
> [info] Resolving org.fusesource.jansi#jansi;1.4 ...
> [info] Done updating.
> [info] Updating {file:/Users/**/**/codegen/sbt-swagger-codegen-examples/project/}root...
> [info] Resolving eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT ...
> [warn] Unable to reparse eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT from sonatype-snapshots, using Mon Jul 04 17:22:22 EEST 2016
> [warn] Choosing sonatype-snapshots for eu.unicredit#sbt-swagger-codegen-lib_2.10;0.0.6-SNAPSHOT
> [info] Resolving eu.unicredit#sbt-swagger-codegen;0.0.6-SNAPSHOT ...
> [warn] Unable to reparse eu.unicredit#sbt-swagger-codegen;0.0.6-SNAPSHOT from sonatype-snapshots, using Mon Jul 04 17:22:17 EEST 2016
> [warn] Choosing sonatype-snapshots for eu.unicredit#sbt-swagger-codegen;0.0.6-SNAPSHOT
> [info] Resolving org.fusesource.jansi#jansi;1.4 ...
> [info] Done updating.
> [info] Compiling 1 Scala source to /Users/wseobseo/zalando/codegen/sbt-swagger-codegen-examples/project/my-extension-plugin/target/scala-2.10/sbt-0.13/classes...
> [info] Set current project to root (in build file:/Users/wseobseo/zalando/codegen/sbt-swagger-codegen-examples/)
> 
> > swaggerCodeGen
> > java.lang.Exception: Provided swagger source dir /Users/**/**/codegen/sbt-swagger-codegen-examples/src/main/swagger doesn't exists
> >   at eu.unicredit.swagger.SwaggerCodegenPlugin$.checkFileExistence(SwaggerCodegenPlugin.scala:409)
> >   at eu.unicredit.swagger.SwaggerCodegenPlugin$.swaggerCodeGenImpl(SwaggerCodegenPlugin.scala:230)
> >   at eu.unicredit.swagger.SwaggerCodegenPlugin$$anonfun$swaggerCodeGenCommand$1.apply(SwaggerCodegenPlugin.scala:215)
> >   at eu.unicredit.swagger.SwaggerCodegenPlugin$$anonfun$swaggerCodeGenCommand$1.apply(SwaggerCodegenPlugin.scala:188)
> >   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
> >   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
> >   at sbt.Command$.process(Command.scala:93)
> >   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
> >   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
> >   at sbt.State$$anon$1.process(State.scala:184)
> >   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
> >   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
> >   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> >   at sbt.MainLoop$.next(MainLoop.scala:96)
> >   at sbt.MainLoop$.run(MainLoop.scala:89)
> >   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
> >   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
> >   at sbt.Using.apply(Using.scala:24)
> >   at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
> >   at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
> >   at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
> >   at sbt.MainLoop$.runLogged(MainLoop.scala:22)
> >   at sbt.StandardMain$.runManaged(Main.scala:54)
> >   at sbt.xMain.run(Main.scala:29)
> >   at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
> >   at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
> >   at xsbt.boot.Launch$.run(Launch.scala:109)
> >   at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
> >   at xsbt.boot.Launch$.launch(Launch.scala:117)
> >   at xsbt.boot.Launch$.apply(Launch.scala:18)
> >   at xsbt.boot.Boot$.runImpl(Boot.scala:41)
> >   at xsbt.boot.Boot$.main(Boot.scala:17)
> >   at xsbt.boot.Boot.main(Boot.scala)
> > [error] java.lang.Exception: Provided swagger source dir /Users/wseobseo/zalando/codegen/sbt-swagger-codegen-examples/src/main/swagger doesn't exists
> > [error] Use 'last' for the full log.

**Comment by fralken** [comment]
You can either run `compile` from the root project, which automatically invokes swaggerCodGen, swaggerClientCodeGen (in client) and swaggerServerCodGen (in server) in client and server projects, or manually switch to each project (e.g `project client` and `project server`) and run swagger commands from them.

Invoking swaggerCodeGen from the root project doesn't work, since it is only an empty container for the real client and server projects.

**Comment by fralken** [comment]
@andreaTP I agree 👍

**Comment by wontheone1** [comment]
@fralken OK I will try later, but I think before you update the version of snapshot, run 'SBT' and then 'swaggerCodeGen' builded somethings not giving the errors. So did you intend to change the steps to how to use this example? Because in the Readme.md it 's still run 'SBT' and then 'swaggerCodeGen'.

**Comment by andreaTP** [comment]
@wontheone1 the REadme.md says to execute the commands into client and server that is quite common using a [sbt multiproject](http://www.scala-sbt.org/0.13/docs/Multi-Project.html)

**Comment by fralken** [comment]
I modified the Readme, please see if it's easier to understand now

**Comment by wontheone1** [comment]
@fralken, with new Readme, I can see how we can use this example. Thank you I think the new Readme is much better. @andreaTP, sorry my experience with Scala itself is very short(1 month), I will check what sbt multiproject is !

**Comment by skasar-mdsol** [comment]
updateOptions := updateOptions.value.withLatestSnapshots(false) 
Add above to build.sbt

**Comment by fralken** [comment]
What is it for?
